/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.vhxdemo;

public final class R {
    public static final class array {
        public static final int AB=0x7f080004;
        public static final int Q=0x7f080002;
        public static final int QV=0x7f080003;
        public static final int epcs=0x7f080000;
        public static final int pref_example_list_titles=0x7f080005;
        public static final int pref_example_list_values=0x7f080006;
        public static final int pref_sync_frequency_titles=0x7f080007;
        public static final int pref_sync_frequency_values=0x7f080008;
        public static final int sessionKV=0x7f080001;
    }
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
        public static final int margin_in_line=0x7f050002;
    }
    public static final class drawable {
        public static final int acm_inputbox=0x7f020000;
        public static final int bg_btn=0x7f020001;
        public static final int bg_btn_normal=0x7f020002;
        public static final int bg_btn_press=0x7f020003;
        public static final int bg_edittext=0x7f020004;
        public static final int bg_edittext_disable=0x7f020005;
        public static final int bg_edittext_focused=0x7f020006;
        public static final int bg_edittext_normal=0x7f020007;
        public static final int bg_input=0x7f020008;
        public static final int bg_tab_normal=0x7f020009;
        public static final int btn=0x7f02000a;
        public static final int btn_selector=0x7f02000b;
        public static final int color_tab_selected=0x7f02000c;
        public static final int connected=0x7f02000d;
        public static final int disconnected=0x7f02000e;
        public static final int edittext_background=0x7f02000f;
        public static final int ic_bluetooth=0x7f020010;
        public static final int ic_bluetooth_connected=0x7f020011;
        public static final int ic_bluetooth_search=0x7f020012;
        public static final int ic_btn=0x7f020013;
        public static final int ic_btn_press=0x7f020014;
        public static final int ic_expand=0x7f020015;
        public static final int ic_flash_off=0x7f020016;
        public static final int ic_launcher=0x7f020017;
        public static final int ic_off=0x7f020018;
        public static final int ic_on=0x7f020019;
        public static final int ic_radio_checked=0x7f02001a;
        public static final int ic_radio_select=0x7f02001b;
        public static final int ic_radio_unchecked=0x7f02001c;
        public static final int ic_unnormal=0x7f02001d;
        public static final int input=0x7f02001e;
        public static final int input_bar_bg=0x7f02001f;
        public static final int inventory_btn_press=0x7f020020;
        public static final int inventory_press=0x7f020021;
        public static final int inventory_pressed=0x7f020022;
        public static final int light_off=0x7f020023;
        public static final int light_on=0x7f020024;
        public static final int radio_selected=0x7f020025;
        public static final int spinner_selector=0x7f020026;
        public static final int stop_btn_press=0x7f020027;
        public static final int stop_press=0x7f020028;
        public static final int stop_pressed=0x7f020029;
        public static final int tab_bg=0x7f02002a;
        public static final int tb=0x7f02002b;
        public static final int txt_bg=0x7f02002c;
    }
    public static final class id {
        public static final int RelativeLayout1=0x7f0a0001;
        public static final int RelativeLayout13=0x7f0a000d;
        public static final int RelativeLayout_inventory=0x7f0a0040;
        public static final int RelativeLayout_link=0x7f0a0048;
        public static final int action_settings=0x7f0a0054;
        public static final int btn_access=0x7f0a0003;
        public static final int btn_disconnect=0x7f0a004b;
        public static final int btn_inventory=0x7f0a0042;
        public static final int btn_mask=0x7f0a0011;
        public static final int btn_scan=0x7f0a004a;
        public static final int checkBoxTest=0x7f0a003b;
        public static final int checkBox_data=0x7f0a0014;
        public static final int data1=0x7f0a0013;
        public static final int device_list=0x7f0a004c;
        public static final int edit_data=0x7f0a0015;
        public static final int edit_data_len=0x7f0a001b;
        public static final int edit_epc=0x7f0a0010;
        public static final int edit_passwd=0x7f0a0006;
        public static final int edit_start=0x7f0a001a;
        public static final int edit_timeout=0x7f0a002d;
        public static final int group_lang=0x7f0a0036;
        public static final int ic_connect_status=0x7f0a000e;
        public static final int include1=0x7f0a0002;
        public static final int include2=0x7f0a0041;
        public static final int include5=0x7f0a000c;
        public static final int list_rfid=0x7f0a0044;
        public static final int radioGroup_op=0x7f0a0007;
        public static final int radio_autolink=0x7f0a001e;
        public static final int radio_ch=0x7f0a0038;
        public static final int radio_chechshock=0x7f0a0022;
        public static final int radio_check_update=0x7f0a0039;
        public static final int radio_detectsound=0x7f0a001f;
        public static final int radio_eng=0x7f0a0037;
        public static final int radio_kill=0x7f0a000b;
        public static final int radio_lock=0x7f0a000a;
        public static final int radio_read=0x7f0a0008;
        public static final int radio_singletag=0x7f0a0021;
        public static final int radio_skipname=0x7f0a0020;
        public static final int radio_write=0x7f0a0009;
        public static final int realtabcontent=0x7f0a001c;
        public static final int s=0x7f0a0000;
        public static final int scroll_config=0x7f0a001d;
        public static final int seekBar1=0x7f0a002f;
        public static final int spinner_ab=0x7f0a0027;
        public static final int spinner_epc=0x7f0a0018;
        public static final int spinner_q=0x7f0a002a;
        public static final int spinner_s=0x7f0a0026;
        public static final int status=0x7f0a004d;
        public static final int status_detect=0x7f0a0019;
        public static final int status_on=0x7f0a004e;
        public static final int status_rx=0x7f0a0051;
        public static final int status_tx=0x7f0a0050;
        public static final int textView2=0x7f0a0030;
        public static final int text_hd_version=0x7f0a0035;
        public static final int text_hd_version_title=0x7f0a0033;
        public static final int text_power=0x7f0a0031;
        public static final int text_sofe_version_title=0x7f0a0032;
        public static final int text_sw_version=0x7f0a0034;
        public static final int text_txpower=0x7f0a002e;
        public static final int text_ver=0x7f0a003a;
        public static final int txt_connect_status=0x7f0a003f;
        public static final int txt_count=0x7f0a0043;
        public static final int txt_count_item=0x7f0a0047;
        public static final int txt_data_title=0x7f0a0012;
        public static final int txt_detect=0x7f0a0017;
        public static final int txt_device_mac=0x7f0a003e;
        public static final int txt_device_name=0x7f0a003c;
        public static final int txt_location_title=0x7f0a0016;
        public static final int txt_no_title=0x7f0a0046;
        public static final int txt_on=0x7f0a004f;
        public static final int txt_passwd=0x7f0a0005;
        public static final int txt_q=0x7f0a0029;
        public static final int txt_queryparamtitle=0x7f0a0023;
        public static final int txt_rfid=0x7f0a0045;
        public static final int txt_rx=0x7f0a0053;
        public static final int txt_session=0x7f0a0024;
        public static final int txt_status=0x7f0a000f;
        public static final int txt_timeout=0x7f0a002c;
        public static final int txt_tx=0x7f0a0052;
        public static final int w=0x7f0a003d;
        public static final int w2=0x7f0a0004;
        public static final int wrap=0x7f0a0049;
        public static final int wrap_q=0x7f0a0028;
        public static final int wrap_spins=0x7f0a0025;
        public static final int wrap_timeout=0x7f0a002b;
    }
    public static final class layout {
        public static final int access=0x7f030000;
        public static final int access_data=0x7f030001;
        public static final int access_location=0x7f030002;
        public static final int activity_main=0x7f030003;
        public static final int config=0x7f030004;
        public static final int device_list_item=0x7f030005;
        public static final int fff=0x7f030006;
        public static final int inventory=0x7f030007;
        public static final int inventory_item_list=0x7f030008;
        public static final int link=0x7f030009;
        public static final int power=0x7f03000a;
        public static final int status=0x7f03000b;
        public static final int testtab=0x7f03000c;
    }
    public static final class menu {
        public static final int main=0x7f090000;
    }
    public static final class string {
        public static final int access_tab=0x7f07002b;
        public static final int action_settings=0x7f070002;
        public static final int app_name=0x7f070001;
        public static final int autolink=0x7f070017;
        public static final int btn_access=0x7f070003;
        public static final int cancel=0x7f070059;
        public static final int checkTest=0x7f070061;
        public static final int checkshock=0x7f07001f;
        public static final int config_tab=0x7f07002d;
        public static final int connected=0x7f070028;
        public static final int content_description_detect_status=0x7f070024;
        public static final int count_lable=0x7f070015;
        public static final int data_hint=0x7f07000a;
        public static final int detect=0x7f07000c;
        public static final int detectsound=0x7f07001a;
        public static final int dialog_title_alert=0x7f070013;
        public static final int disconnect=0x7f070012;
        public static final int hdversion=0x7f070023;
        public static final int hello_blank_fragment=0x7f070016;
        public static final int hint_addr_start=0x7f07000d;
        public static final int hint_data_len=0x7f07000e;
        public static final int inventory=0x7f070014;
        public static final int inventory_tab=0x7f07002c;
        public static final int kill=0x7f070008;
        public static final int label_passwd=0x7f070004;
        public static final int link_tab=0x7f07002a;
        public static final int lock=0x7f070007;
        public static final int mac_title=0x7f070021;
        public static final int mask=0x7f070010;
        public static final int msg_Exitbox_BtnCancal=0x7f070060;
        public static final int msg_Exitbox_BtnOK=0x7f07005f;
        public static final int msg_Exitbox_Context=0x7f07005e;
        public static final int msg_Exitbox_Title=0x7f07005d;
        public static final int msg_ReadWordBlock_timeout=0x7f070053;
        public static final int msg_ReadWordBlock_title=0x7f070052;
        public static final int msg_addr_must_be_hex=0x7f07004a;
        public static final int msg_already_connect=0x7f070037;
        public static final int msg_blocklock_fail=0x7f07004d;
        public static final int msg_blocklock_succ=0x7f07004c;
        public static final int msg_blocklock_timeout=0x7f07004e;
        public static final int msg_bt_not_enable=0x7f070038;
        /**  message 
         */
        public static final int msg_bt_not_support=0x7f07002e;
        public static final int msg_check_update_fail=0x7f07005a;
        public static final int msg_command_fail=0x7f07003e;
        public static final int msg_connect_fail=0x7f07003b;
        public static final int msg_connected=0x7f070039;
        public static final int msg_connecting=0x7f07003a;
        public static final int msg_cur_version=0x7f070054;
        public static final int msg_data_must_be_hex=0x7f070040;
        public static final int msg_device_not_connect=0x7f07003d;
        public static final int msg_download_apk_fail=0x7f07005b;
        public static final int msg_epc_must_larger_zero=0x7f070045;
        public static final int msg_erase_fail=0x7f070048;
        public static final int msg_erase_ok=0x7f070047;
        public static final int msg_erase_timeout=0x7f070049;
        public static final int msg_fail_to_connect=0x7f070030;
        public static final int msg_find_new_version=0x7f070055;
        public static final int msg_inventory_stoping=0x7f07003c;
        public static final int msg_kill_fail=0x7f070043;
        public static final int msg_kill_succ=0x7f070042;
        public static final int msg_kill_timeout=0x7f070044;
        public static final int msg_len_must_be_hex=0x7f07004b;
        public static final int msg_ok=0x7f07002f;
        public static final int msg_paired=0x7f070032;
        public static final int msg_paring=0x7f070031;
        public static final int msg_passwd_len_must_eight=0x7f070046;
        public static final int msg_passwd_must_be_hex=0x7f070041;
        public static final int msg_read_config_fail=0x7f070035;
        public static final int msg_scan_over=0x7f070033;
        public static final int msg_scaning=0x7f070034;
        public static final int msg_soft_update=0x7f070056;
        public static final int msg_timeout=0x7f07003f;
        public static final int msg_update=0x7f070057;
        public static final int msg_update_later=0x7f070058;
        public static final int msg_waring=0x7f070036;
        public static final int msg_wirtewordblock_fail=0x7f070050;
        public static final int msg_wirtewordblock_succ=0x7f07004f;
        public static final int msg_wirtewordblock_timeout=0x7f070051;
        public static final int notconnected=0x7f070029;
        public static final int pref_default_display_name=0x7f070067;
        public static final int pref_description_social_recommendations=0x7f070065;
        /**  Example settings for Data & Sync 
         */
        public static final int pref_header_data_sync=0x7f070069;
        /**  Strings related to Settings 
 Example General settings 
         */
        public static final int pref_header_general=0x7f070063;
        /**  Example settings for Notifications 
         */
        public static final int pref_header_notifications=0x7f07006c;
        public static final int pref_ringtone_silent=0x7f07006f;
        public static final int pref_title_add_friends_to_messages=0x7f070068;
        public static final int pref_title_display_name=0x7f070066;
        public static final int pref_title_new_message_notifications=0x7f07006d;
        public static final int pref_title_ringtone=0x7f07006e;
        public static final int pref_title_social_recommendations=0x7f070064;
        public static final int pref_title_sync_frequency=0x7f07006a;
        public static final int pref_title_system_sync_settings=0x7f07006b;
        public static final int pref_title_vibrate=0x7f070070;
        public static final int queryparam=0x7f070018;
        public static final int radio_check_update=0x7f07005c;
        public static final int radio_lang_chinese=0x7f070027;
        public static final int radio_lang_eng=0x7f070026;
        public static final int read=0x7f070005;
        public static final int scan=0x7f070011;
        public static final int session=0x7f070019;
        public static final int singletag=0x7f07001d;
        public static final int skipname=0x7f07001c;
        public static final int softversion_title=0x7f070022;
        public static final int status=0x7f07000f;
        public static final int stop=0x7f07001e;
        public static final int str_data=0x7f070009;
        public static final int text_ver=0x7f070000;
        public static final int timeout=0x7f07001b;
        public static final int title_access_location=0x7f07000b;
        public static final int title_activity_config_freference=0x7f070062;
        public static final int txpower=0x7f070020;
        public static final int txt_Q_title=0x7f070025;
        public static final int update_url=0x7f070071;
        public static final int write=0x7f070006;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.


    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.



    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060001;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060002;
        public static final int radio_select=0x7f060003;
        public static final int radio_style=0x7f060000;
    }
    public static final class xml {
        public static final int chinese=0x7f040000;
        public static final int config=0x7f040001;
        public static final int english=0x7f040002;
        public static final int pref_data_sync=0x7f040003;
        public static final int pref_general=0x7f040004;
        public static final int pref_notification=0x7f040005;
    }
}
